version: "3.8"
services:
  order-service:
    container_name: order-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: "host.docker.internal:9092"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db.lwoiyulwmuaybduusrxe.supabase.co:5432/postgres?sslmode=require"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "gna5Jpt&*7U!s@+"
      SERVER_PORT: 8081
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
