version: "3.8"

services:
  order-service:
    container_name: order-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      # Use the Kafka already running on the VM (published on 9092).
      # If you’ve exposed Kafka on another port (e.g., 9094), change it here.
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP:-host.docker.internal:9092}
      # Optional: activate your Spring profile
      # SPRING_PROFILES_ACTIVE: prod
    # Ensure Linux Docker can reach the host via 'host.docker.internal'
    extra_hosts:
      - "host.docker.internal:host-gateway"
