spring:
  datasource:
    url: jdbc:postgresql://db.lwoiyulwmuaybduusrxe.supabase.co:5432/postgres?sslmode=require
    username: postgres
    password: gna5Jpt&*7U!s@+
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update   # or validate / none in production
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: 10.0.0.111:9092
    admin:
      auto-create: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: order-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"


server:
  port: 8081


