name: Build & Deploy Order Service

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ensure gradlew is executable (fix CRLF if needed)
        run: |
          if command -v dos2unix >/dev/null 2>&1; then :; else sudo apt-get update && sudo apt-get install -y dos2unix; fi
          dos2unix gradlew || true
          chmod +x gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build JAR with Gradle
        run: ./gradlew --no-daemon clean build -x test

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: order-service-jar
          path: build/libs/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: order-service-jar
          path: build/libs/

      - name: Copy files to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: opc
          key: ${{ secrets.VM_SSH_KEY }}
          source: "build/libs/*.jar,Dockerfile,docker-compose.yml"
          target: "~/order-service"

      - name: Deploy on VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: opc
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd ~/order-service
            docker compose down
            docker compose build --no-cache
            docker compose up -d
